### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tongson** [cloudwu/lua-array#1]
Hello,
Is this MIT-licensed?

Thanks for this very useful Lua module.
Regards.

**Comment by tongson** [comment]
In Lua 5.3 the behavior of a sparse array can be replicated by iterating via:
`for n=1, #t do`

So the advantage of this module is the built-in pairs metamethod?

Please correct me if I misunderstood.

**Comment by cloudwu** [comment]
The license is the same with lua, it's MIT.

In lua 5.3,  #t of the table with nil is undefined ; and for this module, it's certainly  to return the largest numeric key.

See http://www.lua.org/manual/5.3/manual.html#3.4.7

> When t is a sequence, #t returns its only border, which corresponds to the intuitive notion of the length of the sequence. When t is not a sequence, #t can return any of its borders. (The exact one depends on details of the internal representation of the table, which in turn can depend on how the table was populated and the memory addresses of its non-numeric keys.)

And the pairs for the sparse array can iterator in ascending order. For the lua 5.3, the pairs would be out of order when you iterator a table is not a sequence.

**Comment by tongson** [comment]
Thanks for the pointers.
Regards.
